### ISSUE TITLE
DHCP server not working with a network USB adapter

### ISSUE THREAD

**Issue by gildasio** [pi-hole/docker-pi-hole#1413]
This is a: **Bug**  

## Details

I configured pi-hole dashboard to be accessed through a http reverse proxy. This way I need pihole to use bridge network mode but also I need its DHCP server. To everything works I use a DHCP relay as suggest here:

- https://docs.pi-hole.net/docker/dhcp/#docker-pi-hole-with-a-bridge-networking
- https://github.com/pi-hole/docker-pi-hole/issues/320
- https://discourse.pi-hole.net/t/dhcp-with-docker-compose-and-bridge-networking/17038

My DHCP relay configuration is pretty simple:

- Dockerfile:

```
FROM alpine:latest
RUN apk --no-cache add dhcp-helper
EXPOSE 67 67/udp
ENTRYPOINT ["dhcp-helper", "-n"]
```

- docker-compose.yml:

```
...
  dhcphelper:
    build: ./dhcp-helper
    restart: unless-stopped
    network_mode: "host"
    command: -s 172.41.100.100
    cap_add:
      - NET_ADMIN
...
```

All this configuration works just fine in my original setup. When power on the machine it gets its IP from pihole DHCP server and provides other services I run on this machine.

Nowadays I need to migrate to a new machine. This new machine does not have an embedded network interface so I need to use a USB adapter. After all configuration when power on the machine it does not get any IP from pihole.

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: **ArchLinux**
  * Hardware: PC
  * Kernel Architecture: x86/amd64
  * Docker Install Info and version: 
    - Software source: OS provided package
    - Supplimentary Software: None
  * Hardware architecture: x86

2. docker-compose.yml:

```
version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: 'America/Bahia'
      PIHOLE_DNS_: "208.67.222.222;208.67.220.220" # OpenDNS as Upstream
      FTLCONF_LOCAL_IPV4: '192.168.1.7'
      WEBTHEME: "default-darker"
      DHCP_ACTIVE: "true"
      DHCP_START: "192.168.1.10"
      DHCP_END: "192.168.1.200"
      DHCP_ROUTER: "192.168.1.1"
      DNSMASQ_LISTENING: "all"
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
      - './etc-lighttpd:/etc/lighttpd'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      backend:
        ipv4_address: '172.41.100.100'

  dhcphelper:
    build: ./dhcp-helper
    restart: unless-stopped
    network_mode: "host"
    command: -s 172.41.100.100
    cap_add:
      - NET_ADMIN

networks:
  backend:
    ipam:
      config:
        - subnet: 172.41.100.0/16
```

> `dhcphelper`'s Dockerfile is above.

```
sudo docker-compose up -d
```

3. Use an USB interface instead one physically attached to the machine.

4. Reboot the machine

## These common fixes didn't work for my issue
- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x] I have tried running without my volume data mounts to eliminate volumes as the cause

Add any other debugging steps you've taken or theories on root cause that may help:

- If I setup a static ip using `ip a addr ...` and route `ip r add ...` then others devices on network can get its IP properly
- In the previous machine, where everything works, If I unplug the cable and power on the machine, the interface does not get any IP
- In the previous machine, where everything works, If I plug the USB adapter with the cable connected in it and power on the machine, the interface does not get any IP

Because of these tests I thing there is something related to be an USB interface or similar configuration.

- This way my current solution is to set the USB interface a static IP using systemd. This way everything works just fine when booting the server.
```[tasklist]
### Tasks
```

**Comment by PromoFaux** [comment]
Have you exposed port 67? From the docker compose example on the Readme file:


>     `  - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server`

**Comment by gildasio** [comment]
Commenting to keep it open. '-'
